import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import SessionWrapper from '@/components/SessionWrapper';
import Sidebar from "@/components/Sidenav/Sidenav";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex h-screen`}
      >
        <Sidebar />

         <main className="flex-1 p-1 ml-64 md:ml-0">
         {/* Wrap application with SessionProvider */}
         <SessionWrapper>
          {children}
         </SessionWrapper>
         </main>
      </body>
    </html>
  );
}
